Config = {}

Config.RestrictVehicles = true -- Keep to true to only allow the ONX vehicles listed below to use the menu

Config.AllowedVehicles = {
    [GetHashKey('onx_polalamo')] = true,
    [GetHashKey('onx_polgrang')] = true,
    [GetHashKey('onx_polgrang2')] = true,
    [GetHashKey('onx_polmerit')] = true,
    [GetHashKey('onx_polmerit3')] = true,
    [GetHashKey('onx_poltulip')] = true,
    [GetHashKey('onx_polvigero')] = true,
    [GetHashKey('onx_polaleu')] = true,
    [GetHashKey('onx_polcara')] = true,
    [GetHashKey('onx_poldom')] = true,
    [GetHashKey('onx_polmonar')] = true,
    [GetHashKey('onx_polsand')] = true,
    [GetHashKey('onx_polsandsc')] = true,
    [GetHashKey('onx_polsandxl')] = true,
    [GetHashKey('onx_polsandh')] = true,
    [GetHashKey('onx_polscout')] = true,
    [GetHashKey('onx_polscout2')] = true,
    [GetHashKey('onx_poltavros')] = true,
    [GetHashKey('onx_polbison4')] = true,
    [GetHashKey('onx_polbison')] = true,
    [GetHashKey('onx_polbison2')] = true,
    [GetHashKey('onx_polbison3')] = true,
    [GetHashKey('onx_polbuff')] = true,
    [GetHashKey('onx_polbuffhf')] = true,
    [GetHashKey('onx_poldorado2')] = true,
    [GetHashKey('onx_poldorado')] = true,
    [GetHashKey('onx_polgaunt')] = true,
    [GetHashKey('onx_polcava')] = true,
    [GetHashKey('onx_polvstr')] = true,
    [GetHashKey('onx_polcon')] = true,
    [GetHashKey('onx_polkandra')] = true,
    [GetHashKey('onx_polinvict')] = true,
    [GetHashKey('onx_polinvict2')] = true,
    [GetHashKey('onx_polsem')] = true,
    [GetHashKey('onx_polterm')] = true,
    [GetHashKey('onx_polterm2')] = true,
    [GetHashKey('onx_polregent')] = true,
    [GetHashKey('onx_polregentxl')] = true,
    [GetHashKey('onx_polstalk')] = true,
    [GetHashKey('onx_polverus')] = true,
}

Config.ModTypes = {
    aero = 0,
    frontbumper = 1,
    rearbumper = 2,
    skirt = 3,
    callsign_a = 5,
    grille = 6,
    bonnet = 7,
    driverspot = 8,
    passengerspot = 9,
    antenna_ray = 10,
    vanity_plate = 26,
    trim_lights = 27,
    laptop = 28,
    weapons = 30,
    seats = 32,
    radar = 34,
    rambar = 35,
    lockbox = 37,
    engineblock = 39,
    fittings = 41,
    arch_covers = 42,
    aerials = 43,
    trim = 44,
    tank = 45,
    doors = 46,
    liveries = 48,
    lightbars = 49,
}

Config.Menu = {
    { id = 'aero',          displayName = 'Aero' },
    { id = 'frontbumper',   displayName = 'Front Bumper' },
    { id = 'rearbumper',    displayName = 'Rear Bumper' },
    { id = 'skirt',         displayName = 'Skirt' },
    { id = 'grille',         displayName = 'Grille' },
    { id = 'engineblock',   displayName = 'Engine Block' },
    { id = 'bonnet',        displayName = 'Bonnet (Hood)' },
    { id = 'driverspot',    displayName = 'Driver Spotlight' },
    { id = 'passengerspot', displayName = 'Passenger Spotlight' },
    { id = 'antenna_ray',   displayName = 'Antenna Ray' },
    { id = 'vanity_plate',  displayName = 'Vanity Plate (Police Trunk Badge)' },
    { id = 'trim_lights',   displayName = 'Trim (More Lights)' },
    { id = 'laptop',        displayName = 'Ornaments (Laptop Screen)' },
    { id = 'weapons',       displayName = 'Dials (Gunracks)' },
    { id = 'seats',         displayName = 'Seats (Window Bars/K9 Seats)' },
    { id = 'radar',         displayName = 'Shifter (Radar)' },
    { id = 'rambar',        displayName = 'Plaques (Rambar)' },
    { id = 'lockbox',       displayName = 'Trunk (Lockbox)' },
    { id = 'fittings',      displayName = 'Fittings (Roof Lights)' }, 
    { id = 'doors',         displayName = 'Door Tags' }, 
    { id = 'liveries',      displayName = 'Liveries' }, 
    { id = 'lightbars',     displayName = 'Lightbars' }, 

}

